// This file is auto-generated by Specta.

// Run: cargo test --workspace --test specta_export



export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

export type ThemeTokens = { bg: string; fg: string; accent: string }

export type WindowState = { id: string; x: number; y: number; width: number; height: number; maximized: boolean; focused: boolean; route: string }

export type WidgetState = { id: string; kind: string; props: JsonValue }

/**
 * Single Source of Truth - cały stan aplikacji
 */
export type AppState = { version: number; windows: Partial<{ [key in string]: WindowState }>; widgets: Partial<{ [key in string]: WidgetState }>; theme: ThemeTokens }

export type Action = { WidgetUpdate: { widget_id: string; field: string; value: JsonValue } } | { WindowResize: { window_id: string; width: number; height: number } } | { WindowMove: { window_id: string; x: number; y: number } } | { Navigate: { window_id: string; route: string } } | { ThemeChanged: { tokens: ThemeTokens } }