use std::fs;
use std::path::PathBuf;
use venner_core::{
    Action, AppState, ImportResult, PersistedAppState, ThemeTokens, ValidationReport, WidgetState,
    WindowState,
};

#[test]
fn specta_export() {
    let out_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../packages/core/src/types");
    fs::create_dir_all(&out_dir).expect("failed to create types output directory");

    let out_file = out_dir.join("generated.ts");

    let mut lines = Vec::new();
    lines.push("// This file is auto-generated by Specta.".to_string());
    lines.push("// Run: cargo test --workspace --test specta_export".to_string());
    lines.push(String::new());

    lines.push(
        specta_typescript::export::<serde_json::Value>(&Default::default())
            .expect("failed to export JsonValue"),
    );
    lines.push(
        specta_typescript::export::<ThemeTokens>(&Default::default())
            .expect("failed to export ThemeTokens"),
    );
    lines.push(
        specta_typescript::export::<WindowState>(&Default::default())
            .expect("failed to export WindowState"),
    );
    lines.push(
        specta_typescript::export::<WidgetState>(&Default::default())
            .expect("failed to export WidgetState"),
    );
    lines.push(
        specta_typescript::export::<AppState>(&Default::default())
            .expect("failed to export AppState"),
    );
    lines.push(
        specta_typescript::export::<PersistedAppState>(&Default::default())
            .expect("failed to export PersistedAppState"),
    );
    lines.push(
        specta_typescript::export::<ValidationReport>(&Default::default())
            .expect("failed to export ValidationReport"),
    );
    lines.push(
        specta_typescript::export::<ImportResult>(&Default::default())
            .expect("failed to export ImportResult"),
    );
    lines.push(
        specta_typescript::export::<Action>(&Default::default()).expect("failed to export Action"),
    );

    let output = lines.join("\n\n");
    fs::write(out_file, output).expect("failed to write generated.ts");
}
